package service

import (
	"context"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"time"

	"firewall-gitops/webhook-soar/internal/repository"
)

type Processor struct {
	repo          *repository.GitLabRepository
	yamlProcessor *YAMLProcessor
}

func NewProcessor(repo *repository.GitLabRepository, yamlProc *YAMLProcessor) *Processor {
	return &Processor{
		repo:          repo,
		yamlProcessor: yamlProc,
	}
}

// ProcessAlert orchestrates full workflow
func (p *Processor) ProcessAlert(ctx context.Context, ip, ticketID, reason string) (int, error) {
	logger := slog.With("ip", ip, "ticket_id", ticketID)
	logger.Info("processing alert")

	// Sanitize ticket ID for branch naming
	sanitizedTicketID := p.sanitizeTicketID(ticketID)

	// 1. Clone repository
	repoPath, err := p.repo.CloneToTemp(ctx)
	if err != nil {
		return 0, fmt.Errorf("clone failed: %w", err)
	}

	// Ensure cleanup happens even if processing fails
	defer func() {
		if cleanupErr := p.repo.Cleanup(repoPath); cleanupErr != nil {
			logger.Warn("failed to cleanup temp directory", "error", cleanupErr)
		}
	}()

	// 2. Create feature branch
	branchName := p.generateBranchName(sanitizedTicketID)
	if err := p.repo.CreateBranch(ctx, repoPath, branchName); err != nil {
		return 0, fmt.Errorf("create branch failed: %w", err)
	}

	// 3. Update YAML
	added, err := p.yamlProcessor.AddIP(repoPath, ip)
	if err != nil {
		return 0, fmt.Errorf("yaml update failed: %w", err)
	}

	if !added {
		logger.Info("ip already in blocklist", "ip", ip)
		// IP already exists - still success, no MR needed
		return 0, nil
	}

	// 4. Commit changes
	commitMsg := p.generateCommitMessage(ip, ticketID, reason)
	if err := p.repo.CommitChanges(ctx, repoPath, commitMsg); err != nil {
		return 0, fmt.Errorf("commit failed: %w", err)
	}

	// 5. Push branch
	if err := p.repo.PushBranch(ctx, repoPath, branchName); err != nil {
		return 0, fmt.Errorf("push failed: %w", err)
	}

	// 6. Create merge request
	mrTitle, mrDesc := p.generateMRContent(ip, ticketID, reason)
	mrID, err := p.repo.CreateMergeRequest(ctx, branchName, mrTitle, mrDesc)
	if err != nil {
		return 0, fmt.Errorf("create MR failed: %w", err)
	}

	logger.Info("alert processed successfully",
		"branch", branchName,
		"merge_request_id", mrID)

	return mrID, nil
}

// sanitizeTicketID removes unsafe characters for branch naming
func (p *Processor) sanitizeTicketID(ticketID string) string {
	// Remove or replace unsafe characters
	unsafe := []string{
		"/", "\\", ":", "*", "?", "\"", "<", ">", "|",
		" ", "\t", "\n", "\r",
	}

	sanitized := ticketID
	for _, char := range unsafe {
		sanitized = strings.ReplaceAll(sanitized, char, "-")
	}

	// Remove consecutive dashes
	for strings.Contains(sanitized, "--") {
		sanitized = strings.ReplaceAll(sanitized, "--", "-")
	}

	// Trim leading/trailing dashes
	sanitized = strings.Trim(sanitized, "-")

	// Limit length
	if len(sanitized) > 50 {
		sanitized = sanitized[:50]
	}

	return sanitized
}

// generateBranchName creates a unique branch name
func (p *Processor) generateBranchName(ticketID string) string {
	timestamp := time.Now().Unix()
	return fmt.Sprintf("soar-block-%s-%d", ticketID, timestamp)
}

// generateCommitMessage creates a standardized commit message
func (p *Processor) generateCommitMessage(ip, ticketID, reason string) string {
	if reason == "" {
		reason = "No reason provided"
	}
	return fmt.Sprintf("feat: block IP %s from SOAR ticket %s\n\nReason: %s", ip, ticketID, reason)
}

// generateMRContent creates merge request title and description
func (p *Processor) generateMRContent(ip, ticketID, reason string) (string, string) {
	title := fmt.Sprintf("Block IP %s (SOAR: %s)", ip, ticketID)

	if reason == "" {
		reason = "No reason provided"
	}

	description := fmt.Sprintf(`## SOAR Alert

**Ticket ID:** %s
**Blocked IP:** %s
**Reason:** %s

This merge request was automatically generated by the SOAR webhook service.

### Changes
- Added IP to firewall blocklist
- No manual intervention required

### Verification
- [ ] Verify IP is malicious
- [ ] Confirm CIDR notation is correct
- [ ] Test firewall rule after deployment

---`, ticketID, ip, reason)

	return title, description
}

// ValidateTicketID checks if ticket ID is in valid format
func (p *Processor) ValidateTicketID(ticketID string) error {
	// Basic validation - not empty and reasonable length
	if strings.TrimSpace(ticketID) == "" {
		return fmt.Errorf("ticket ID cannot be empty")
	}

	// Try to extract numeric portion
	parts := strings.Fields(ticketID)
	for _, part := range parts {
		if _, err := strconv.Atoi(part); err == nil {
			return nil // Found numeric part, ticket ID seems valid
		}
	}

	// If no numeric part found, still accept but log warning
	slog.Warn("ticket ID has no numeric component", "ticket_id", ticketID)
	return nil
}
