apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soar-webhook.fullname" . }}
  labels:
    {{- include "soar-webhook.labels" . | nindent 4 }}
type: Opaque
data:
  gitlab-token: {{ required "GitLab token is required" .Values.secrets.gitlabToken | b64enc | quote }}